ALTER TABLE data_resource ADD citable_agent VARCHAR(2048) NULL;
ALTER TABLE data_resource ADD display_name VARCHAR(1024) NULL;
ALTER TABLE data_resource ADD contributor BIT(1) NULL;
ALTER TABLE data_resource ADD last_harvested datetime NULL;
ALTER TABLE data_resource ADD repatriation_country VARCHAR(255) NULL;
ALTER TABLE data_resource ADD is_private TINYINT(3) NULL;
ALTER TABLE data_resource ADD suitable_for TEXT NULL;
ALTER TABLE data_resource ADD data_collection_protocol_name TEXT NULL;
ALTER TABLE data_resource ADD data_collection_protocol_doc TEXT NULL;
ALTER TABLE data_resource ADD suitable_for_other_detail TEXT NULL;
CREATE INDEX uid_idx ON collection(uid);
CREATE INDEX uid_idx ON data_hub(uid);
CREATE INDEX uid_idx ON data_provider(uid);
CREATE INDEX uid_idx ON data_resource(uid);
CREATE INDEX uid_idx ON institution(uid);
ALTER TABLE provider_map DROP KEY collection_id;
ALTER TABLE collection MODIFY attributions VARCHAR(255);
ALTER TABLE data_hub MODIFY attributions VARCHAR(255);
ALTER TABLE data_hub MODIFY attributions VARCHAR(255) NOT NULL;
ALTER TABLE data_provider MODIFY attributions VARCHAR(255);
ALTER TABLE data_resource MODIFY attributions VARCHAR(255);
ALTER TABLE institution MODIFY attributions VARCHAR(255);
ALTER TABLE data_resource MODIFY citation LONGTEXT;
ALTER TABLE data_resource MODIFY connection_parameters LONGTEXT;
ALTER TABLE data_resource MODIFY data_generalizations LONGTEXT;
ALTER TABLE data_resource MODIFY default_darwin_core_values LONGTEXT;
ALTER TABLE collection MODIFY focus LONGTEXT;
ALTER TABLE data_hub MODIFY focus VARCHAR(2048);
ALTER TABLE data_provider MODIFY focus LONGTEXT;
ALTER TABLE data_resource MODIFY focus LONGTEXT;
ALTER TABLE institution MODIFY focus VARCHAR(2048);
ALTER TABLE collection MODIFY guid VARCHAR(45);
ALTER TABLE data_hub MODIFY guid VARCHAR(45);
ALTER TABLE data_provider MODIFY guid VARCHAR(45);
ALTER TABLE data_resource MODIFY guid VARCHAR(100);
ALTER TABLE institution MODIFY guid VARCHAR(45);
ALTER TABLE data_resource MODIFY harvesting_notes LONGTEXT;
ALTER TABLE data_resource MODIFY information_withheld LONGTEXT;
ALTER TABLE collection MODIFY keywords LONGTEXT;
ALTER TABLE collection MODIFY kingdom_coverage LONGTEXT;
ALTER TABLE collection MODIFY latitude DECIMAL(13, 10) NULL;
ALTER TABLE data_provider MODIFY latitude DECIMAL(13, 10) NULL;
ALTER TABLE data_resource MODIFY latitude DECIMAL(13, 10) NULL;
ALTER TABLE institution MODIFY latitude DECIMAL(13, 10) NULL;
ALTER TABLE collection MODIFY longitude DECIMAL(13, 10) NULL;
ALTER TABLE data_provider MODIFY longitude DECIMAL(13, 10) NULL;
ALTER TABLE data_resource MODIFY longitude DECIMAL(13, 10) NULL;
ALTER TABLE institution MODIFY longitude DECIMAL(13, 10) NULL;
ALTER TABLE data_resource ALTER make_contact_public DROP DEFAULT;
ALTER TABLE data_hub MODIFY member_collections LONGTEXT;
ALTER TABLE data_hub MODIFY member_data_resources LONGTEXT;
ALTER TABLE data_hub MODIFY member_institutions LONGTEXT;
ALTER TABLE data_hub MODIFY members LONGTEXT;
ALTER TABLE data_resource MODIFY mobilisation_notes LONGTEXT;
ALTER TABLE collection MODIFY name VARCHAR(128);
ALTER TABLE institution MODIFY name VARCHAR(128);
ALTER TABLE sequence MODIFY name VARCHAR(45);
ALTER TABLE collection MODIFY network_membership LONGTEXT;
ALTER TABLE data_provider MODIFY network_membership LONGTEXT;
ALTER TABLE data_resource MODIFY network_membership LONGTEXT;
ALTER TABLE audit_log MODIFY new_value VARCHAR(2048);
ALTER TABLE collection MODIFY notes LONGTEXT;
ALTER TABLE data_hub MODIFY notes VARCHAR(2048);
ALTER TABLE data_provider MODIFY notes LONGTEXT;
ALTER TABLE data_resource MODIFY notes LONGTEXT;
ALTER TABLE institution MODIFY notes VARCHAR(2048);
ALTER TABLE audit_log MODIFY old_value VARCHAR(2048);
ALTER TABLE data_resource MODIFY permissions_document LONGTEXT;
ALTER TABLE audit_log MODIFY persisted_object_id BIGINT;
ALTER TABLE collection MODIFY phone VARCHAR(45);
ALTER TABLE data_hub MODIFY phone VARCHAR(45);
ALTER TABLE data_provider MODIFY phone VARCHAR(45);
ALTER TABLE data_resource MODIFY phone VARCHAR(45);
ALTER TABLE institution MODIFY phone VARCHAR(45);
ALTER TABLE sequence MODIFY prefix VARCHAR(5);
ALTER TABLE collection MODIFY pub_description LONGTEXT;
ALTER TABLE data_hub MODIFY pub_description LONGTEXT;
ALTER TABLE data_provider MODIFY pub_description LONGTEXT;
ALTER TABLE institution MODIFY pub_description LONGTEXT;
ALTER TABLE data_resource ALTER public_archive_available SET DEFAULT 0;
ALTER TABLE data_resource MODIFY rights LONGTEXT;
ALTER TABLE collection MODIFY scientific_names LONGTEXT;
ALTER TABLE data_resource MODIFY status VARCHAR(255);
ALTER TABLE data_resource MODIFY status VARCHAR(255) NULL;
ALTER TABLE collection MODIFY sub_collections LONGTEXT;
ALTER TABLE collection MODIFY taxonomy_hints LONGTEXT;
ALTER TABLE data_hub MODIFY taxonomy_hints VARCHAR(1024);
ALTER TABLE data_provider MODIFY taxonomy_hints LONGTEXT;
ALTER TABLE data_resource MODIFY taxonomy_hints LONGTEXT;
ALTER TABLE institution MODIFY taxonomy_hints VARCHAR(1024);
ALTER TABLE collection MODIFY tech_description LONGTEXT;
ALTER TABLE data_hub MODIFY tech_description LONGTEXT;
ALTER TABLE data_provider MODIFY tech_description LONGTEXT;
ALTER TABLE data_resource MODIFY tech_description LONGTEXT;
ALTER TABLE institution MODIFY tech_description LONGTEXT;
CREATE INDEX collection_id ON provider_map(collection_id);
GO
